### ISSUE TITLE
Warning when the URL doesn't include www

### ISSUE THREAD

**Issue by ryotayamanaka** [pitagora-network/home-learning#1]

**Comment by manabuishii** [comment]
https://home-learning.online/
is called apex domain.

GitHub help is here for such a situation.

[Managing a custom domain for your GitHub Pages site \- GitHub Docs](https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain)

**Comment by ryotayamanaka** [comment]
Resolved. Thank you @manabuishii !
